### ISSUE TITLE
Days and Months missing

### ISSUE THREAD

**Issue by julesjacobsen** [TheJacksonLaboratory/PhenopacketGenerator#11]
The drop-downs for age only allow 11 months and 30 days. This should be 12 and 31 respectively.

**Comment by pnrobinson** [comment]
well, 12 months = 1 year and 31 days = 1 month....

**Comment by julesjacobsen** [comment]
Sorry - I was thinking of dates e.g. Dec 31th, not durations.

**Comment by julesjacobsen** [comment]
So for a 1 year old we need to be able to express P1Y0M0D currently it's only possible to express P1Y1M1D or P0Y11M30D *if* you click a value in the months or days drop-down menu. i.e. you can't set any the years, months or days value to zero having previously selected a non-zero value.

**Comment by pnrobinson** [comment]
fixed
