### ISSUE TITLE
Approved terms should not contain duplicates

### ISSUE THREAD

**Issue by julesjacobsen** [TheJacksonLaboratory/PhenopacketGenerator#12]
In the window which pops up from the 'Enter HPO terms' button, the bottom right table titled 'Approved terms' should not contain duplicate HPO terms. Currently it it possible to add the same term more than once. On output it would be nice to sort the terms by id, for the sake of consistency and reproducibility.

**Comment by pnrobinson** [comment]
@julesjacobsen AFAIK you can enter the same term multiple times but the output is a set of unique terms. Have you observed duplicates in the output, that would be worrisome!

**Comment by ielis** [comment]
I'll make sure that the terms are sorted by id on output.

**Comment by julesjacobsen** [comment]
@pnrobinson yes, that's why I opened the ticket! I've been using master to test on. Replacing PgModel.phenotypes with a TreeSet and implementing Comparable<PgOntologyClass> in PgOntologyClass ought to solve things. I added them by selecting the same term once from the HPO tree browser panel and the other from the text-mining panel. I know, artificial, but still users... 

```json
{
  "id": "voyager",
  "subject": {
    "id": "warf",
    "sex": "MALE"
  },
  "phenotypicFeatures": [{
    "type": {
      "id": "HP:0001363",
      "label": "Craniosynostosis"
    },
    "evidence": [{
      "evidenceCode": {
        "id": "ECO:0000302",
        "label": "author statement used in manual assertion"
      }
    }]
  }, {
    "type": {
      "id": "HP:0001363",
      "label": "Craniosynostosis"
    },
    "evidence": [{
      "evidenceCode": {
        "id": "ECO:0000302",
        "label": "author statement used in manual assertion"
      }
    }]
  }],
  "metaData": {
    "created": "2019-11-28T15:02:41.147Z",
    "createdBy": "julesj",
    "resources": [{
      "id": "hp",
      "name": "human phenotype ontology",
      "url": "http://purl.obolibrary.org/obo/hp.owl",
      "version": "unknown HPO version",
      "namespacePrefix": "HP",
      "iriPrefix": "http://purl.obolibrary.org/obo/HP_"
    }, {
      "id": "eco",
      "name": "Evidence and Conclusion Ontology",
      "url": "http://purl.obolibrary.org/obo/eco.owl",
      "version": "2019-10-16",
      "namespacePrefix": "ECO",
      "iriPrefix": "http://purl.obolibrary.org/obo/ECO_"
    }],
    "phenopacketSchemaVersion": "1.0.0-RC3"
  }
}
```

**Comment by pnrobinson** [comment]
Thanks for the suggestion , I have implemented it.
