### ISSUE TITLE
Always override equals() and hashCode() in value-type classes (toString() is always nice too)

### ISSUE THREAD

**Issue by julesjacobsen** [TheJacksonLaboratory/PhenopacketGenerator#16]
e.g. `PgOntologyClass` - if you create two of these with the same parameters they will not be considered equals and cannot be safely used as keys in maps or as values in sets which rely on these methods.

For simple immutable value classes consider using the [Immutables](https://immutables.github.io/) library:

```java
@Value.Immutable
abstract class AbstractPgOntologyClass {
    abstract String id;
    abstract String label;
    abstract boolean not_observed
}
```
will auto-generate the class for you with all the equals(), hashCode(), toString, getters, builders and all the rest.

**Comment by pnrobinson** [comment]
thanks for pointing this out -- the code was written in a hurry :-0  I added the methods.

**Comment by julesjacobsen** [comment]
Hopefully coming in Java 14 - [records](https://openjdk.java.net/jeps/359).

Codes like this:

```java 
record PgOntologyClass (String id, String label, boolean not_observed) {
}
```

adds all the boilerplate for you!

**Comment by pnrobinson** [comment]
@julesjacobsen  -- we definitely need to start moving to more modern Javas -- let's see if we can start to modularize in 2020 and move to Java 14 by the end of next year --

**Comment by julesjacobsen** [comment]
Yes, but perhaps settling on an LTS release when it arrives would be the optimal cadence. According to  https://adoptopenjdk.net/support.html the next LTS after 11 is going to be after Sept 2022 so that will be version 19?! Anyway, I think most people are not happy upgrading their Java version every 6 months. Especially not in clinical and/or corporate environments, but an LTS upgrade would be more palatable.
