### ISSUE TITLE
HPO text-mining analysis terms API

### ISSUE THREAD

**Issue by lingluodlut** [TheJacksonLaboratory/PhenopacketGenerator#20]
Hi, I only want to use 'HPO text-mining analysis terms' function to extract HPO terms from text in our code without GUI. Do you provide the API of the function?  Or how can I use the function in our code?
Thanks a lot.

**Comment by ielis** [comment]
Hi @lingluodlut, we use SciGraph REST API to perform the text mining and to identify position of candidate HPO terms. The docs for the API are [here](https://scigraph-ontology.monarchinitiative.org/scigraph/docs/).

An example how to use the API in Java can be found [here](https://github.com/monarch-initiative/HpoTextMining/blob/b00c6daad054de52d9ef71abb2e6c7dcbfc161b7/hpotextmining-core/src/test/java/org/monarchinitiative/hpotextmining/core/miners/scigraph/SciGraphTermMinerTest.java#L107). HpoTextMining is the library that is being used by PhenopacketGenerator behind the scenes.
I would recommend to run the `askMonarchServerTest` test in debugger to see how it works.

I hope this is enough information to give you what you need and get you started. Please let me know if that's not the case.

Cheers,
Daniel

**Comment by lingluodlut** [comment]
OK, I will try it. Thanks again.
