### ISSUE TITLE
Cannot export, will not accept age string

### ISSUE THREAD

**Issue by cmungall** [TheJacksonLaboratory/PhenopacketGenerator#4]
![image](https://user-images.githubusercontent.com/50745/68497753-23b1ba00-020a-11ea-9abe-d29332c60e9a.png)

Is there a special syntax that needs added?

I would recommend validation at data entry time rather than export time

**Comment by pnrobinson** [comment]
Um, 60 what(s)? :-0
We are demanding the iso duration format (8601). We should make three fields for year, month, and day and then convert the format to P21Y4M17D or whatever, I will add something.

**Comment by pnrobinson** [comment]
I replaced the text field with combo boxes for Year, Month, and Day (I think it is fine to omit week for this demo). Now a correct iso String is generated.
