### ISSUE TITLE
hp.obo path is not saved

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketGenerator#5]
The path is not being saved correctly (Macintosh) and so the user needs to reenter the path each time the program is started.

**Comment by ielis** [comment]
The path is being saved correctly, I checked it on my Mac. You can validate that by inspecting logging statements & by seeing text mining button and export phenopacket button changing to enabled. 
The issue is with updating of the label. I'll take look at it

**Comment by pnrobinson** [comment]
Thanks, this is working fine!
