### ISSUE TITLE
Evidence code

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketGenerator#8]
Currently, ,we are using this evidence code:
```
"id": "ECO:0000033",
"label": "author statement supported by traceable reference"
```
But the code is designed to denote that the statement refers to a published paper.
We need a code to say that the biocurator is saying this without more evidence (we do not know how this tool will be used). Even the superclass 'author statement' refers to a paper.

The nearest I can find is https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000302&viewMode=All&siblings=false

author statement used in manual assertion

I am changing this, but please shout if there is something more appropriate.

**Comment by LCCarmody** [comment]
Maybe I am not quite understanding, but couldn't you use ECO_0000305 'curator inference used in manual assertion'?

**Comment by justaddcoffee** [comment]
> We need a code to say that the biocurator is saying this without more evidence (we do not know how this tool will be used). 

Being that you want something generic, what about ECO_0000006 'experimental evidence'

**Comment by julesjacobsen** [comment]
I don't know the background for the issue, but can't the user decide from a drop-down list?

**Comment by pnrobinson** [comment]
Well, the evidence is not necessary curator inference (to the extent that not everything is inference which is debatable). It is also rarely experimental. ECO might need a new code for clinical observation. Perhaps it is OK to leave this very general for now, but once we start to make this software more robust, we should talk about how to capture evidence better.

**Comment by julesjacobsen** [comment]
One thought - if the text is a copy-pasted from a published case report with a pubmed id, e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2734025/ it would be good to be able to add the link as an externalReference:

```json
{
  "evidenceCode": {
    "id": "ECO:0006017",
    "label": "author statement from published clinical study used in manual assertion"
  },
  "reference": {
    "id": "PMID:16614535",
    "description": "A Case of Pfeiffer Syndrome"
  }
}
```

**Comment by pnrobinson** [comment]
Well, we should probably link out to the full HPOCaseAnnotator for PubMed annotations. We need to have a plan for where to go from here. @ielis thoughts?

**Comment by ielis** [comment]
IMO since `evidence` is an attribute of `PhenotypicFeature`, there should a way to specify the evidence code for each phenotype term individually. If we really want to be as precise as possible.

I am not sure that's the aim of this app though.

**Comment by pnrobinson** [comment]
I think we do not need to be this sophisticated for this app. At somepoint we can add more features to the TextMining module as needed!

**Comment by julesjacobsen** [comment]
So why not leave the evidence off completely for this release and then add a fully-implemented version to the next one? This way output won't be wrong, but it could merely be more complete.

**Comment by pnrobinson** [comment]
I think the current codes are OK. We should leave further modifications to a more fully featured tool.
